version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: harold
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskappdatabase
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: harold@zurita.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "16543:80"
    depends_on:
      - postgres

volumes:
  postgres-data: